apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-ruby-application.fullname" . }}
  labels:
    {{- include "my-ruby-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-ruby-application.name" . }}
