name: Deploy pipeline
on:
  push:
    branches:
      - 'main'
      - 'production'
jobs:
  deploy_development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download Commit ID Artifact
        uses: actions/download-artifact@v2
        with:
          name: commit-id

      - name: Read Commit ID from Artifact
        run: |
          COMMIT_ID=$(cat commit-id.txt)
          echo "Using commit ID: $COMMIT_ID"

#      - name: Set up Kubectl
#        uses: azure/setup-kubectl@v1
#        with:
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}
#          version: 'latest'

      - name: Deploy to development
        if: github.ref == 'refs/heads/main'
        run: |
          #kubectl apply -f manifests/main.yaml
          echo "the tag will use $COMMIT_ID"
          

  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Commit ID Artifact
        uses: actions/download-artifact@v2
        with:
          name: commit-id

      - name: Read Commit ID from Artifact
        run: |
          COMMIT_ID=$(cat commit-id.txt)
          echo "Using commit ID: $COMMIT_ID"

#      - name: Set up Kubectl
#        uses: azure/setup-kubectl@v1
#        with:
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}
#          version: 'latest'

      - name: Deploy to Production
        run: |
          #kubectl apply -f manifests/production.yaml
          echo "the tag will use $COMMIT_ID"